kind: Deployment
apiVersion: apps/v1
metadata:
  name: odh-easybuild
  labels:
    app: odh-easybuild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odh-easybuild
      app.kubernetes.io/part-of: odh-easybuild
      deployment: odh-easybuild
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odh-easybuild
        app.kubernetes.io/part-of: odh-easybuild
        deployment: odh-easybuild
    spec:
      initContainers:
        - resources:
            limits:
              cpu: '2'
              memory: 4096Mi
            requests:
              cpu: 500m
              memory: 500Mi
          name: easybuild-init
          imagePullPolicy: IfNotPresent
          image: 'quay.io/guimou/easybuild-ubi8-py39:latest'
          volumeMounts:
            - mountPath: /opt/apps/easybuild
              name: easybuild-data
          command:
            - /opt/app-root/src/easybuild_install.sh
      containers:
        - resources:
            limits:
              cpu: '8'
              memory: 8192Mi
            requests:
              cpu: 500m
              memory: 500Mi
          name: easybuild-run
          imagePullPolicy: IfNotPresent
          image: 'quay.io/guimou/easybuild-ubi8-py39:latest'
          volumeMounts:
            - mountPath: /opt/apps/easybuild
              name: easybuild-data
          command:
            - /opt/app-root/src/easybuild_run.sh
      volumes:
        - name: easybuild-data
          persistentVolumeClaim:
            claimName: easybuild-data
      terminationGracePeriodSeconds: 30
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
