services:
  jupyterlab:
    ## image: ghcr.io/maastrichtu-ids/jupyterlab:latest
    build: 
      context: .
      dockerfile: base/Dockerfile

    user: root
    # user: "1000"
    # user: ${UID}
    ports:
      - 8888:8888
    # volumes:
      ## Share volumes for jupyterlab:
      # - ./data/work:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=password
      ## Download repo:
      # - GIT_URL=https://github.com/MaastrichtU-IDS/dsri-demo